config/routes.rb
Rails.application.routes.draw do
  root to: 'gardens#index'

  resources :gardens do
    resources :plants, only: :create
  end

  resources :plants, only: :destroy do
    resources :taggings, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true

  has_many :plants, dependent: :destroy
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden # adds a presence validation on the garden_id foreign key

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :name, presence: true
end

app/models/plant_tag.rb
class PlantTag < ApplicationRecord
  belongs_to :plant
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :plants, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :plant
  belongs_to :tag

  # We don't want the same tag associated multiple times to the same plant
  validates :tag, uniqueness: { scope: :plant }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:show, :edit, :update, :destroy]

  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
    @plant = Plant.new
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens
  def create
    @garden = Garden.new(garden_params)

    if @garden.save
      redirect_to @garden, notice: 'Garden was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gardens/1
  def update
    if @garden.update(garden_params)
      redirect_to @garden, notice: 'Garden was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gardens/1
  def destroy
    @garden.destroy
    redirect_to gardens_url, notice: 'Garden was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def garden_params
      params.require(:garden).permit(:name, :banner_url)
    end
end

app/controllers/plant_tags_controller.rb
class PlantTagsController < ApplicationController
  def new
    @plant = Plant.find(params[:plant_id])
    @plant_tag = PlantTag.new
  end

  def create
    @plant = Plant.find(params[:plant_id])
    plant_tag_params[:tag_id].each do |tag_id|
      plant_tag = PlantTag.new(tag_id: tag_id)
      plant_tag.plant = @plant
      plant_tag.save
    end
    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_tag_params
    params.require(:plant_tag).permit(tag_id: [])
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render "gardens/show"
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    garden = @plant.garden
    @plant.destroy
    redirect_to garden_path(garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
  def new
    # Our route is nested, so we have something like this:
    # /plants/:plant_id/taggings/new

    # If the URL path looks confusing, try reading it like this (in reverse order):
    #                 I want
    # /new         <- a new tagging
    # /taggings    <- on the index of taggings
    # /:plant_id   <- of the plant that goes by id
    # /plants      <- in the index of plants

    # So we have to find the plant by the :plant_id we find in the URL
    @plant = Plant.find(params[:plant_id])
    #  We also need our new shiny Tagging our user is going to later create
    @tagging = Tagging.new
  end

  def create
    # We need the plant from the current path again.
    # But noticed how this repeats on both #new and #create? We could make this a set_plant
    # method tied to before_action on new and create.
    # Reminder: https://kitt.lewagon.com/knowledge/lectures/05-Rails%2F02-Rails-CRUD#/0/8/3
    @plant = Plant.find(params[:plant_id])

    # We now take a new Taggings again and fill it with the info the user selected on the form
    # Check the #tagging_params on the bottom of this controller to see what it's doing.
    @tagging = Tagging.new(tagging_params)

    # We need to then associate this new @tagging to the current @plant 
    # This is needed because the tagging_params has ONLY the params chosen by the user on the form
    @tagging.plant = @plant

    # We try to save the new tagging. This will be false if it doesn't pass the validation.
    if @tagging.save
      # If its saved, we take the user back to the garden to which the plant belongs
      redirect_to garden_path(@plant.garden)
    else
      # If it fails we render #new again, showing the form with some errors
      render :new
    end
  end

  private

  # The web is scary, so we need to allow the user to send only the information we permit
  def tagging_params
    params.require(:tagging).permit(:tag_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gardens/edit.html.erb
<h1>Editing Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Show', @garden %> |
<%= link_to 'Back', gardens_path %>

app/views/gardens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gardens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Banner url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gardens.each do |garden| %>
      <tr>
        <td><%= garden.name %></td>
        <td><%= garden.banner_url %></td>
        <td><%= link_to 'Show', garden %></td>
        <td><%= link_to 'Edit', edit_garden_path(garden) %></td>
        <td><%= link_to 'Destroy', garden, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Garden', new_garden_path %>

app/views/gardens/new.html.erb
<h1>New Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Back', gardens_path %>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @garden.banner_url %>');">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>

<div class="container mt-3">
  <div class="cards">
    <% @garden.plants.each do |plant| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= plant.image_url %>')">

          <div class="card-tags">
            <% plant.tags.each do |tag| %>
              <span><%= tag.name %></span>
            <% end %>
            <%= link_to '+', new_plant_tagging_path(plant) %>
          </div>        

          <%= plant.name %>
          <%= link_to "+", plant_path(plant), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link" %>
        </div>
    <% end %>
  </div>

  <div class="mt-3 row justify-content-center">
    <div class="col-4">
      <h4>Add a plant:</h4>
      <%= simple_form_for [ @garden, @plant ] do |f| %>
        <%= f.input :name, placeholder: "Palm tree" %>
        <%= f.input :image_url, placeholder: "https://some_nice_image_found_on_google.jpg" %>
        <%= f.submit "Add", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plant_tags/new.html.erb
<div class="container">
  <h1>Select a tag:</h1>
  <%= simple_form_for [@plant, @plant_tag] do |form| %>
    <%= form.association :tag, collection: Tag.all, input_html: { multiple: true, class: 'select2' }, include_hidden: false %>
    <%= form.submit %>
  <% end %>
</div>

app/views/taggings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <h1>Add new tag to <%= @plant.name %></h1>
      <%= simple_form_for [@plant, @tagging] do |form| %>
        <%# Next line is simple_form magic to give us a select with all the tags in our DB %>
        <%= form.association :tag %>

        <%# Advanced challenge, folks! %>
        <%# So far our select shows Tag.all (it defaults the collection parameter to it). %>
        <%# But... what if we wanted to show only the tags not yet associated with the current plant? %>
        <%# Tip: you're gonna need #left_joins. %>
        <%# Tip2: Tie it in a nice active_record scope. So you could call it like this: Tag.untagged_by(@plant) %>
        <%#= form.association :tag, collection: Tag.all %>

        <%= form.submit %>
      <% end %>
    </div>
  </div>
</div>